-- MySQL Script generated by MySQL Workbench
-- Sat Aug 27 22:24:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema budget_diary
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `budget_diary` ;

-- -----------------------------------------------------
-- Schema budget_diary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budget_diary` DEFAULT CHARACTER SET utf8 ;
USE `budget_diary` ;

-- -----------------------------------------------------
-- Table `budget_diary`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget_diary`.`category` ;

CREATE TABLE IF NOT EXISTS `budget_diary`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget_diary`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget_diary`.`transaction` ;

CREATE TABLE IF NOT EXISTS `budget_diary`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NULL,
  `date_transaction` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget_diary`.`outcome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget_diary`.`outcome` ;

CREATE TABLE IF NOT EXISTS `budget_diary`.`outcome` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `transaction_id` INT NULL,
  `detail_item` TEXT NULL,
  `amount` INT NOT NULL,
  `date_created` DATETIME NOT NULL DEFAULT CURDATE(),
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_transaction_has_category_category1_idx` (`category_id` ASC) ,
  INDEX `fk_daily_spend_transaction1_idx` (`transaction_id` ASC) ,
  CONSTRAINT `fk_transaction_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `budget_diary`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_spend_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `budget_diary`.`transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget_diary`.`income`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budget_diary`.`income` ;

CREATE TABLE IF NOT EXISTS `budget_diary`.`income` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_id` INT NOT NULL,
  `date_created` DATE NOT NULL DEFAULT CURDATE(),
  `amount` INT NOT NULL,
  `type` ENUM('BANK BCA', 'BANK ALADIN', 'GIFT', 'CASH', 'GOPAY', 'OVO', 'SHOPEE PAY') NOT NULL,
  `detail` TEXT NULL,
  PRIMARY KEY (`id`, `transaction_id`),
  INDEX `fk_income_transaction1_idx` (`transaction_id` ASC) ,
  CONSTRAINT `fk_income_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `budget_diary`.`transaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `budget_diary`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `budget_diary`;
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (1, 'Makan');
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (2, 'Kos');
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (3, 'Transport');
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (4, 'Kebutuhan harian');
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (5, 'Hedon');
INSERT INTO `budget_diary`.`category` (`id`, `name`) VALUES (6, 'Bayar hutang');

COMMIT;

